import Image from "next/image";
import { Metadata } from "next";
import InvoiceForm from "../components/InvoiceForm";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <InvoiceForm />
    </main>
  );
}
